# theme: jekyll-theme-hacker
remote_theme: thelehhman/texture
title: Опенсорсный блог
description: Блог про Linux, Bash и другие информационные технологии
permalink: /:title
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


