# theme: jekyll-theme-hacker
remote_theme: thelehhman/texture
title: Опенсорсный блог
description: Блог про Linux, Bash и другие информационные технологии
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
show_excerpts: true
excerpt_separator: <!--more-->  #Should work OK with posts exported from Wordpress
paginate: 10
paginate_path: "/page:num/"
header_pages:
  - index.md
  - categories.md

texture:
  title: Опенсорсный блог
  tagline: Блог про Linux, Bash и другие информационные технологии
  style: black
  showNav: true
  showPicker: false
  social_links:
    github: mnorin
