# theme: jekyll-theme-hacker
remote_theme: thelehhman/texture
title: Опенсорсный блог
description: Блог про Linux, Bash и другие информационные технологии
permalink: /:title
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
show_excerpts: true
texture:
  title: Опенсорсный блог
  tagline: Блог про Linux, Bash и другие информационные технологии
  style: black
  showNav: true
  showPicker: false
  github: mnorin

